import {
  FaReact,
  FaNodeJs,
  FaJsSquare,
  FaHtml5,
  FaCss3Alt,
} from "react-icons/fa";

import {
  SiReact,
  SiNextdotjs,
  SiExpress,
  SiMongodb,
  SiRedux,
  SiFirebase,
  SiTypescript,
  SiTailwindcss,
  SiGraphql,
  SiMysql,
  SiPostman,
  SiAndroidstudio,
  SiXcode,
  SiExpo,
  SiGithub,
} from "react-icons/si";

export const skillsData = [
  {
    name: "React Native",
    icon: SiReact,
    color: "#61DAFB",
    percentage: 95,
    tags: ["Expo", "Navigation", "Redux"],
  },
  {
    name: "React.js",
    icon: FaReact,
    color: "#61DAFB",
    percentage: 94,
    tags: ["Hooks", "Context API", "SPA"],
  },
  {
    name: "Next.js",
    icon: SiNextdotjs,
    color: "#000000",
    percentage: 92,
    tags: ["SSR", "App Router", "SEO"],
  },
  {
    name: "JavaScript",
    icon: FaJsSquare,
    color: "#F7DF1E",
    percentage: 95,
    tags: ["ES6+", "Async", "DOM"],
  },
  {
    name: "TypeScript",
    icon: SiTypescript,
    color: "#3178C6",
    percentage: 86,
    tags: ["Types", "Interfaces", "Generics"],
  },
  {
    name: "Redux Toolkit",
    icon: SiRedux,
    color: "#764ABC",
    percentage: 93,
    tags: ["RTK", "Thunk", "Slices"],
  },
  {
    name: "Node.js",
    icon: FaNodeJs,
    color: "#339933",
    percentage: 88,
    tags: ["REST API", "JWT", "Express"],
  },
  {
    name: "Express.js",
    icon: SiExpress,
    color: "#000000",
    percentage: 87,
    tags: ["Middleware", "Routing", "API"],
  },
  {
    name: "MongoDB",
    icon: SiMongodb,
    color: "#47A248",
    percentage: 86,
    tags: ["Collections", "Aggregation", "Mongoose"],
  },
  {
    name: "MySQL",
    icon: SiMysql,
    color: "#4479A1",
    percentage: 80,
    tags: ["Queries", "Joins", "Database"],
  },
  {
    name: "Firebase",
    icon: SiFirebase,
    color: "#FFCA28",
    percentage: 91,
    tags: ["FCM", "Auth", "Firestore"],
  },
  {
    name: "GraphQL",
    icon: SiGraphql,
    color: "#E10098",
    percentage: 82,
    tags: ["Apollo", "Queries", "Mutations"],
  },
  {
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    color: "#06B6D4",
    percentage: 92,
    tags: ["Responsive", "Dark Mode", "UI"],
  },
  {
    name: "HTML5",
    icon: FaHtml5,
    color: "#E34F26",
    percentage: 96,
    tags: ["Semantic", "Accessibility", "SEO"],
  },
  {
    name: "CSS3 / SCSS",
    icon: FaCss3Alt,
    color: "#1572B6",
    percentage: 94,
    tags: ["Flexbox", "Grid", "Animations"],
  },
  {
    name: "Git & GitHub",
    icon: SiGithub,
    color: "#181717",
    percentage: 92,
    tags: ["Git Flow", "PR", "Version Control"],
  },
  {
    name: "Postman",
    icon: SiPostman,
    color: "#FF6C37",
    percentage: 90,
    tags: ["REST API", "Testing", "Collections"],
  },
  {
    name: "Android Studio",
    icon: SiAndroidstudio,
    color: "#3DDC84",
    percentage: 88,
    tags: ["APK", "Gradle", "Debugging"],
  },
  {
    name: "Xcode",
    icon: SiXcode,
    color: "#147EFB",
    percentage: 84,
    tags: ["Pods", "IPA", "Simulator"],
  },
  {
    name: "Expo",
    icon: SiExpo,
    color: "#000000",
    percentage: 87,
    tags: ["EAS", "Build", "Development"],
  },
];
